parameters:
    mercure_jwt_secret: '%env(MERCURE_JWT_SECRET)%'
services:
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique des services

    # Transformer pour DTO -> Entité
    App\DataTransformer\PatientGlobalDtoToEntityTransformer:
        arguments:
            $serializer: '@serializer'
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['api_platform.data_transformer']
        
    App\DataPersister\PatientDataPersister:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags: ['api_platform.data_persister']

    # Provider de la personne connectée
    App\State\MeProvider: ~

    App\Security\AuthenticationSuccessHandler:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
            
    App\Serializer\Encoder\MultipartFormDataDecoder:
        arguments:
            - '@request_stack'
        tags:
            - { name: 'serializer.encoder' }

    ApiPlatform\State\ProcessorInterface: '@api_platform.doctrine.orm.state.persist_processor'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
