# config/packages/mercure.yaml
mercure:
  hubs:
    default:
      url: '%env(MERCURE_URL)%'
      public_url: '%env(MERCURE_PUBLIC_URL)%'
      jwt:
        secret: '%env(MERCURE_JWT_SECRET)%'
        algorithm: 'hmac.sha256'
        publish:   ['*']

# mercure:
#     hubs:
#         default:
#             url: '%env(MERCURE_URL)%'
#             public_url: '%env(MERCURE_PUBLIC_URL)%'
#             jwt:
#                 # Fournit directement le JWT wildcard que vous avez généré
#                 value: '%env(MERCURE_JWT_TOKEN)%'
               