nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000']
        # allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'X-CSRF-Token']
        allow_credentials: true
        expose_headers: ['Link', 'X-Pagination-Total-Count', 'X-Pagination-Page-Count', 'Authorization']
        max_age: 3600
        hosts: []
    paths:
        '^/api/': ~
