vich_uploader:
    db_driver: orm # Utilisez "orm" pour Doctrine ORM
    mappings:
        patient_photo:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: Vich\UploaderBundle\Naming\UniqidNamer # Génère un nom de fichier unique
            delete_on_update: true
            delete_on_remove: true