vich_uploader:
    db_driver: orm # Utilisez "orm" pour Doctrine ORM
    mappings:
        patient_photo:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer # Génère un nom de fichier unique
            delete_on_update: true
            delete_on_remove: true

        devis_pdf:
            uri_prefix: /uploads/devis
            upload_destination: '%kernel.project_dir%/public/uploads/devis'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true